### ISSUE TITLE
502 bad gateway sur join.frencherlang.com

### ISSUE THREAD

**Issue by abelards** [erlangparis/erlangparis.github.io#1]
Bonjour,
un souci d'URL ou de déploiement sur http://join.frencherlang.com/ ?
C'est en 502 depuis plus de 24h.
À moins qu'il ne faille montrer son allégeance en passant par XMPP uniquement :)
Merci et cordialement,

**Comment by benoitc** [comment]
c'est fixé. Merci!

**Comment by benoitc** [comment]
oups. j'ai fermé trop vite. Il semble que Slack n'accepte plus les enregistrements actuellement rauchg/slackin#110 . Je suis en train de regarder.

**Comment by benoitc** [comment]
le fix mis en place hier fonctionne. L'intervalle de pollling a été augmenté;

**Comment by abelards** [comment]
Merci ! :revolving_hearts:
